### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by martingg88** [VelbazhdSoftwareLLC/Fruit-Machine-Simulator-with-Excel-Interface#3]
facing the following issue. any idea? 

java -jar Fruit-Machine-Simulator-with-Excel-Interface-all.jar -input ~/Desktop/Game_Sample_001.xlsx -basereels "Base Reels 95.5 RTP" -freereels "Free Reels 95.5 RTP" -initial 87
Execute command:

java Main -input /Users/martin/Desktop/Game_Sample_001.xlsx -basereels Base Reels 95.5 RTP -freereels Free Reels 95.5 RTP -initial 87 

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at eu.veldsoft.slot.simulator.Main.loadGameStructure(Main.java:242)
	at eu.veldsoft.slot.simulator.Main.main(Main.java:629)
	... 11 more
Exception running application eu.veldsoft.slot.simulator.Main

**Comment by TodorBalabanov** [comment]
The sample file was missing images for the symbols. Try it with this one: https://github.com/VelbazhdSoftwareLLC/Fruit-Machine-Simulator-with-Excel-Interface/blob/master/doc/Game_Sample_001.xlsx

**Comment by martingg88** [comment]
ok thanks

**Comment by martingg88** [comment]
But facing another problem regarding to Lines in excel. 

2021-05-12T11:24:15.110+0800 [ERROR] [system.err] java.lang.reflect.InvocationTargetException
2021-05-12T11:24:15.110+0800 [ERROR] [system.err] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-05-12T11:24:15.110+0800 [ERROR] [system.err] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-05-12T11:24:15.110+0800 [ERROR] [system.err] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-05-12T11:24:15.111+0800 [ERROR] [system.err] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-05-12T11:24:15.111+0800 [ERROR] [system.err] 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
2021-05-12T11:24:15.111+0800 [ERROR] [system.err] 	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
2021-05-12T11:24:15.111+0800 [ERROR] [system.err] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-05-12T11:24:15.111+0800 [ERROR] [system.err] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-05-12T11:24:15.111+0800 [ERROR] [system.err] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-05-12T11:24:15.111+0800 [ERROR] [system.err] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-05-12T11:24:15.111+0800 [ERROR] [system.err] 	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
2021-05-12T11:24:15.111+0800 [ERROR] [system.err] Caused by: java.lang.NullPointerException
2021-05-12T11:24:15.111+0800 [ERROR] [system.err] 	at eu.veldsoft.slot.simulator.Main.loadGameStructure(Main.java:278)
2021-05-12T11:24:15.111+0800 [ERROR] [system.err] 	at eu.veldsoft.slot.simulator.Main.main(Main.java:629)
Caused by: java.lang.NullPointerException

**Comment by martingg88** [comment]
Just check your code and i believe excel missing this sheet "Bills Loading".

**Comment by TodorBalabanov** [comment]
Try this one: https://github.com/VelbazhdSoftwareLLC/Fruit-Machine-Simulator-with-Excel-Interface/blob/master/doc/Game_Sample_001.xlsx

**Comment by martingg88** [comment]
it seems like working. lets me check the rest and get back to you. thanks

**Comment by TodorBalabanov** [comment]
Try the visual command. It is also interesting.

**Comment by martingg88** [comment]
ok. thanks
